### ISSUE TITLE
run together with db migrate

### ISSUE THREAD

**Issue by gregdymek** [ilyakatz/data-migrate#102]
is it possible to run together with migration based on timestamp order?
eg. I have db migrations
migration_A_000001
migration_B_000003
and data migraiton:
data_migration_X_000002
is it possible to run it in following order: A, X, C,
best regards

**Comment by ajaxm** [comment]
@gregdymek I believe `rake db:migrate:with_data` does exactly that: it runs (database AND data) migrations ordered by their timestamps, regardless of the type of migration

**Comment by ilyakatz** [comment]
@ajaxm is correct. looks like this issue can be closed
