### ISSUE TITLE
Is there support for multitenancy?

### ISSUE THREAD

**Issue by emersonborges** [ilyakatz/data-migrate#107]
I'm using Postgres with multiples schemas, and after executing a data migration, a table _data_migrations_ was created just for the public schema, not for the others.

**Comment by ilyakatz** [comment]
Hi @emersonborges no, we don't have this in mind. How does rails handle this case for just regular db migrations?

**Comment by christianhellsten** [comment]
If you have two separate Rails applications using the same database and two separate Postgres schemas, you can modify the **schema_search_path** and have one **schema_migrations** table in each schema:

App1 (app1/config/database.yml):
```
...
  database: apps_production
  # Schema search path. The server defaults to $user,public
  schema_search_path: app1,public
```

App2 (app2/config/database.yml):
```
....
  database: apps_production
  # Schema search path. The server defaults to $user,public
  schema_search_path: app2,public
```

In this case two separate **data_migrations** tables would be created, one in each schema, in the same database.

**Comment by ilyakatz** [comment]
hm, data_migrate is using database connection from Rails, so I wonder if this would just work out of the box, have you tried it and did it fail for you?
