### ISSUE TITLE
Conditional migrations capistrano task sometimes ignores changes

### ISSUE THREAD

**Issue by borama** [ilyakatz/data-migrate#110]
I believe there is a small bug in the [checking condition](https://github.com/ilyakatz/data-migrate/blob/master/lib/capistrano/data_migrate/migrate.rb#L10) in the Capistrano task that runs migrations conditionaly.

```ruby
if conditionally_migrate && (
    test("diff -q #{release_path}/db/migrate #{current_path}/db/migrate") ||
    test("diff -q #{release_path}/db/data #{current_path}/db/data")
  )
  info '[deploy:migrate] Skip `deploy:migrate` (nothing changed in db/migrate or db/data)'
else
  info '[deploy:migrate] Run `rake db:migrate:with_data`'
  invoke :'deploy:migrating_with_data'
end
```

From the [SSHkit code](https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/abstract.rb#L57) it seems that the `test` method returns `true` when the given command exits gracefully (i.e. when the `diff` tool finds no changes in the compared directories). But the condition here will succeed even if _one_ of the directories (schema or data migrations) differs due to the `||` operator, thus preventing running migrations unless _both_ directories differ.

I believe there should be an `&&` operator in the condition instead, skipping migrations only if _none_ of the two migration dirs differ.

I can make a PR if you like. Thanks for this wonderful gem!

**Comment by EnomaDebby** [comment]
This has been fixed. Closing
