### ISSUE TITLE
Data Migration version

### ISSUE THREAD

**Issue by yuri-val** [ilyakatz/data-migrate#117]
Is it correct to using `ActiveRecord::Migrator.current_version` to get current data_migration version?
https://github.com/ilyakatz/data-migrate/blob/126e409483d0b867428ae4550b2d05e9b2d3ec60/tasks/databases.rake#L25

As far as I understand, you need to use `DataMigrate::DataMigrator.current_version` here, right?

**Comment by ilyakatz** [comment]
Hm, I think you're right. Looking at the code, it hasn't been touched since it's origination. I think it needs to be cleaned up, will probably get to this after rails 6 compatibility changes.

**Comment by sully7** [comment]
Oops... I didn't look back far enough when I created #201
