### ISSUE TITLE
Can't find capistrano deploy:migrate task after require 'capistrano/data_migrate'

### ISSUE THREAD

**Issue by GuillaumeM59** [ilyakatz/data-migrate#118]
First try to deploy with data_migrations today, installing gem version data_migrate: 5.3.2, capistrano: 3.11.0,
Capfile:
```
...
# require 'capistrano/rails/migrations'
require 'capistrano/data_migrate'
...
```

got backtrace on bundle exec cap staging T & cap staging deploy:check : 

(Backtrace restricted to imported tasks)
cap aborted!
Don't know how to build task 'deploy:migrate' (See the list of available tasks with `rake --tasks`)
Did you mean?  deploy:starting

**Comment by ilyakatz** [comment]
Hm, i'm not too familiar with capistrano piece of this, to be honest. Other contributors added this functionality. @borama @gacha do you know by any chance?

**Comment by borama** [comment]
You should not have commented out the original capistrano migration tasks require in `Capfile`. The cap task in data migration works in the following way (see [source](https://github.com/ilyakatz/data-migrate/blob/master/lib/capistrano/data_migrate/migrate.rb#L4)):

1. it clears the original capistrano task for doing migrations (`deploy:migrate`)
2. it defines its own version of `deploy:migrate` cap task to handle both schema and data migrations

So I guess you get an exception in the first step as capistrano cannot find the original cap task to be cleared.

I wonder what made you comment that line out? Was it perhaps this line in the README (emphasis mine)?

> The gem comes with a capistrano task that can be used _instead_ of `capistrano/rails/migrations`.

If so, the sentence might need a slight rewording, perhaps to something like:

> The gem comes with a capistrano task that overrides tasks in `capistrano/rails/migrations`.

**Comment by GuillaumeM59** [comment]
Exactly, the "instead" word make me comment this line.
without comment this line, deploy:check seems ok

thanks @borama
