### ISSUE TITLE
Data migration is not correctly placed when trailing slash is not present

### ISSUE THREAD

**Issue by wenderjean** [ilyakatz/data-migrate#121]
Actually is possible to change database migrations path like below but accidentally I realized that there is no a fall back in cases of absent trailing slash.

```ruby
DataMigrate.configure do |config|
  config.data_migrations_path = "db/path"
end
```

#### Current behavior

- Generates database migrations in `db/`

#### Expected behavior

- Generates database migrations in `db/path/`

**Comment by EnomaDebby** [comment]
Thanks for the fix @wenderjean. It's published on RubyGems. Closing this
