### ISSUE TITLE
Tag for 5.3.2 version missing

### ISSUE THREAD

**Issue by biow0lf** [ilyakatz/data-migrate#124]
Hello,

Looks like tag for 5.3.2 version missing. Can anyone push missing tag(s)?

**Comment by ilyakatz** [comment]
Do you mean git tags? We don't usually do those. What are you trying to do?

**Comment by biow0lf** [comment]
> Do you mean git tags? We don't usually do those. What are you trying to do?

Read documentation for specific version of `data_migrate`.

**Comment by ilyakatz** [comment]
Sorry, I still don't understand what your asking

**Comment by Qwertie-** [comment]
@ilyakatz If the releases are done with git tags as well you can display the readme files as they were back when the version was released so you can see how to do things on an old version.

**Comment by ilyakatz** [comment]
ok, i'll try to not forget to add git tags on releases as well. thanks
