### ISSUE TITLE
What is the modern version of needs_migration?

### ISSUE THREAD

**Issue by Qwertie-** [ilyakatz/data-migrate#126]
My application was using `DataMigrate::DataMigrator.needs_migration?` This doesn't work anymore in the latest version and I was unable to find where it is now.

**Comment by EnomaDebby** [comment]
@Qwertie- will look into this

**Comment by MaicolBen** [comment]
Related question, is it expected to fail the app if you didn't migrate the last data migration? Because it isn't happening for me

**Comment by EnomaDebby** [comment]
@MaicolBen Can you clarify what failing the app means?

**Comment by MaicolBen** [comment]
This one:
```
Migrations are pending. To resolve this issue, run:

         bin/rails db:migrate RAILS_ENV=development
```

I would like the same but for data, I don't want to a developer to remember when to run data migrations

**Comment by ilyakatz** [comment]
@EnomaDebby is still being worked on?

**Comment by hs-dodufuye** [comment]
Not at the moment

**Comment by ilyakatz** [comment]
@Qwertie- @MaicolBen would you be interested in trying this out with a PR if you still need this functionality?
