### ISSUE TITLE
Rails 6.0.3.beta (or tweaked 5.x) not actually running data migrations

### ISSUE THREAD

**Issue by bbugh** [ilyakatz/data-migrate#133]
The 6.x beta *run* with Rails, but it's not actually doing anything with `db:schema:load:with_data`.

```
rake db:drop db:create db:schema:load:with_data

Dropped database 'rails-6-upgrade-development'
Dropped database 'rails-6-upgrade-test'
Created database 'rails-6-upgrade-development'
Created database 'rails-6-upgrade-test'
```

```
> rake db:migrate:status:with_data

database: rails-6-upgrade-development

 Status    Type    Migration ID   Migration Name
------------------------------------------------------------
   up     schema  20171012183056  Squash post launch 2.0
   up     schema  20171124200429  Do something with something
  down     data   20171124200500  Migrate a thing to some things
   up     schema  20171126233306  Create item data
   up     schema  20171128194833  Remove columns from a thing
   up     schema  20171226205522  Drop things data table
   up     schema  20171226235736  Rename thing price columns
  down     data   20171226235747  Move thing buy price to another thing
```

Since the schema load isn't working, we can't do any development work. We have a number of migrations that are long passed (you can see 2017 there), and running them all from scratch will not work.

**Comment by ilyakatz** [comment]
@EnomaDebby mind taking a look?

**Comment by EnomaDebby** [comment]
Sure

**Comment by bbugh** [comment]
Any thoughts on this? Anything I can do to help? This is the only thing left preventing us from upgrading. Thanks!

**Comment by EnomaDebby** [comment]
Apologies @bbugh. Been very busy and was planning to take a look at this during the weekend. If you have a solution, you can create a PR as well.

**Comment by bbugh** [comment]
@EnomaDebby Thank you for the fast reply! I'm really grateful for the help and this gem.

I spent some time with the code and analyzing #120 before making this issue and unfortunately didn't see anything obvious. As far as I could tell it looks correct. If y'all have any idea on what might be happening I can look at it some more to PR, but I'm stumped.

**Comment by EnomaDebby** [comment]
Looking into this

**Comment by EnomaDebby** [comment]
Hi, @bbugh I've looked into this and `db:schema:load:with_data` loads your schema but doesn't run your data migrations.

**Comment by bbugh** [comment]
Hey @EnomaDebby, that’s correct. It should load the data schema without running the migrations. 

As you can see in the original report, Rails was not seeing the migrations as having been loaded. You can check with `db:migrate:status:with_data`

When we ran `db:migrate:with_data` it would attempt to re-run all data migrations, which is not the desired behavior.

**Comment by EnomaDebby** [comment]
Oh, I see what you mean now.

**Comment by ilyakatz** [comment]
version 6.1.0 released to rubygems!
