### ISSUE TITLE
Rails 6.0.0.rc1 can't generate migration

### ISSUE THREAD

**Issue by marina8915** [ilyakatz/data-migrate#134]
When  rails g data_migration some_name
StandardError: class DataMigrate::Migration < ActiveRecord::Migration[4.2] 

If I create a migration manually, the error is too.
All migrations have ActiveRecord::Migration[6.0]

**Comment by ferdi2005** [comment]
I have this problem too!

**Comment by ilyakatz** [comment]
It seems you're using a version of data_migrate that is not compatible with Rails 6

Make sure to put this in your Gemfile

```gem 'data_migrate', '6.0.3.beta'```

**Comment by ilyakatz** [comment]
Looks like this is resolved, closing
