### ISSUE TITLE
last file in data migration folders are not being inserted on rake tasks

### ISSUE THREAD

**Issue by ChrisCPO** [ilyakatz/data-migrate#137]
When:  `rails c > Dir.glob("db/data/*.rb").to_a.length => 33`

Then: `Rake::Task["db:structure:load:with_data"].execute`

Expected: 
```rails db=# select count(1) from data_migrations;
 count
-------
   33
```

Actually: 
```rails db=# select count(1) from data_migrations;
 count
-------
   32
```

rails 5.2.3 
data_migrate 5.3.2

When have 2 data migration file locations, the data folder and one we implemented after_deploy_migrations. Our count is down by 2, and after inspecting the timestamps were missing the last file from each location. I have also found this issue when loading from one file, count was off by 1.

What are the two hardest things in computer science:
- naming things
- cache invalidation
- off by one errors

**Comment by ilyakatz** [comment]
what is inside `data_schema.rb`? Does it correspond to the data of the last data migration?
