### ISSUE TITLE
Data Migration with Postgres, logging version to wrong table

### ISSUE THREAD

**Issue by mjsommer** [ilyakatz/data-migrate#15]
Hi,

I just setup Data Migrate with Rails 4 and Postgres 9.2, and am having an issue with the version being stored in the wrong table. Even though: 1) I use the '--skip-schema-migration' flag, and 2) create a migration (only) in the db/data folder, when I run 'rake data:migrate', the version is stored in the schema_migrations table, and not data_migrations.

In addition, if I do a 'rake data:migrate:status' after successfully running the migration, the status comes back as 'down', vs 'up'. This is most likely, because the version was listed in the wrong table, to begin with.

I tried building the migration without the '--skip-schema-migration' flag, and got the same results.

Fyi, here is my table info:

abc_development=# \d schema_migrations 
       Table "public.schema_migrations"
 Column  |          Type          | Modifiers 
---------+------------------------+-----------
 version | character varying(255) | not null
Indexes:
    "unique_schema_migrations" UNIQUE, btree (version)

abc_development=# \d data_migrations 
        Table "public.data_migrations"
 Column  |          Type          | Modifiers 
---------+------------------------+-----------
 version | character varying(255) | not null
Indexes:
    "unique_data_migrations" UNIQUE, btree (version)

How can I fix this?

Thanks,
Martin

**Comment by ilyakatz** [comment]
This was resolved in this issue https://github.com/ilyakatz/data-migrate/issues/22. Please check it out and if there are any problems please create a followup issue. 

Thanks for reporting this!
