### ISSUE TITLE
data_migrations table missing primary key

### ISSUE THREAD

**Issue by aandis** [ilyakatz/data-migrate#151]
It would be a good idea to have a primary key on the `data_migrations` table (instead of a unique key) just like [rails has a primary key](https://github.com/rails/rails/pull/23359) on `schema_migrations` table. This would mirror the rails architecture closely.

**Comment by ilyakatz** [comment]
Good call, @aandis. Would you be willing to create a PR for this? I haven't been doing Ruby for a while not so would appreciate the help :)
