### ISSUE TITLE
Minimise Rails dependency footprint

### ISSUE THREAD

**Issue by pmackay** [ilyakatz/data-migrate#167]
I've been using derailed to look at gem footprints. I think because data_migrate has a dependency on the rails gem, it can cause all of the rails gems to be pulled into a project. Would it be possible to have data_migrate only have a dependency on a version of activerecord or another gem that is one of the parts of Rails?

Given that Rails now includes gems like actionmailbox (very large) and actioncable, its not always desirable for these to be pulled in.

**Comment by ilyakatz** [comment]
Hi @pmackay you're probably correct about this, it doesn't need the whole of rails as a dependency. Would you be interesting in creating a PR for this? I haven't worked with Rails for over a year so looking for more contributions from the community
