### ISSUE TITLE
Data migration failing with missing attributes

### ISSUE THREAD

**Issue by anilk914** [ilyakatz/data-migrate#17]
Hi,

We tried using this gem for our application which is already developed long way and in production. We have many models and wanted to populated these tables with some data in QA.

Am getting below missing attribute error. Is this gem tested against 3.2 version? I see people saying it is working fine for them. Just checking if something messed up on my end.

unknown attribute: xxxxxx
../vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:88:in `block in assign_attributes'
../vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:78:in `each'
../vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
../vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/base.rb:497:in `initialize'

-- Thanks

**Comment by ajvargo** [comment]
Given the age, I'm closing this. If its still a problem, please open a new ticket and include the migration that fails along w/ the trace.
