### ISSUE TITLE
v6.8.0 doesn't include code changes 

### ISSUE THREAD

**Issue by y-yagi** [ilyakatz/data-migrate#184]
I checked release contents of `v6.8.0`. But I couldn't detect code changing from `v6.7.0`. It seems that only `VERSION` and `Changelog` were changed.

```diff
$ diff -r data_migrate-6.8.0 data_migrate-6.7.0 
diff -r data_migrate-6.8.0/Changelog.md data_migrate-6.7.0/Changelog.md
3,5d2
< ## 6.8.0
< 
< Specify database name for migrations_paths [lewhit](https://github.com/lewhit)
diff -r data_migrate-6.8.0/lib/data_migrate/version.rb data_migrate-6.7.0/lib/data_migrate/version.rb
2c2
<   VERSION = "6.8.0".freeze
---
>   VERSION = "6.7.0".freeze 
``` 

Is this expected changes?

**Comment by ilyakatz** [comment]
hm, you're right. i'll update changelog but will just leave the version in rubygems, doesn't seem like it's worth it to yank it

thanks for letting me know!

**Comment by y-yagi** [comment]
Thanks for your response!  I confirmed that a new version was released. I'll close this.
