### ISSUE TITLE
No changelog for 7.0.0 release

### ISSUE THREAD

**Issue by TonyArra** [ilyakatz/data-migrate#186]
There's no changelog for the latest major release, which makes me hesitant to update.

**Comment by ilyakatz** [comment]
Change was in dependencies requirement, not in the actual code. 

7.0.0

![image](https://user-images.githubusercontent.com/282514/115273388-55fc6200-a0f4-11eb-99a6-a7807580beb3.png)

6.8.0

![image](https://user-images.githubusercontent.com/282514/115273488-788e7b00-a0f4-11eb-8641-a8ccb881694c.png)
