### ISSUE TITLE
Was 6.8.0 mis-tagged as 7.0.0?

### ISSUE THREAD

**Issue by corroded** [ilyakatz/data-migrate#187]
We have dependebot running and I was double checking the changes. It does seem that way - or am I missing something?

![image](https://user-images.githubusercontent.com/46548/115311766-c95cad00-a1a2-11eb-9b8b-784da9fab09d.png)

The only version bump I see is for 6.8.0 and there is no tag for it.

**Comment by ilyakatz** [comment]
yeah, sorry, there was a mishap with 6.8.0. It's a "dummy" version now. 7.0.0 is the real one that reduces dependencies requirements.
