### ISSUE TITLE
Remove adding of UTF-8 encoding to `db/data_schema.rb`

### ISSUE THREAD

**Issue by bkuhlmann** [ilyakatz/data-migrate#195]
## Overview

When running `rake db:migrate:with_data`, I keep ending up with a `# encoding: UTF-8` pragma at the top of `db/data_schema.rb` file but this pragma isn't necessary since that is the default encoding which causes a bit of a conflict with Rubocop. Would it be possible to remove this pragma in the next version of Data Migrate?

## Screenshots/Screencasts

![iTerm2-mZA8tj4g](https://user-images.githubusercontent.com/50245/124973147-6d0e6a00-dfe8-11eb-8626-69cdfe0036fe.png)

## Steps to Recreate

Remove the UTF pragma and run `rake db:migrate:with_data` on any existing project. Notice that it gets re-inserted at the top of the file.

## Desired Behavior

Would like to not see the pragma inserted each time so that we don't have to exclude this file in our Rubocop configuration.

## Environment

- Ruby 3.0.2
- Data Migrate 7.0.1

**Comment by ilyakatz** [comment]
Yeah, i think these are left overs from old versions of ruby. Want to give it a shot with a PR?

**Comment by bkuhlmann** [comment]
Hey Ilya, I've got a fix in place. Let me know if you need anything else.

**Comment by bkuhlmann** [comment]
:information_source: Closing as this is fixed in 7.0.2.
