### ISSUE TITLE
Is there a configuration to restrict data migrations to only the production environment?

### ISSUE THREAD

**Issue by aaronkelton** [ilyakatz/data-migrate#206]
Is there a way to configure the data migrations to only run in certain environments, e.g. production only? Or does each data migration file basically need to be wrapped in a `if Rails.env.production?` block?

I can see a scenario where a new developer on the team may be tempted to come along and run `rails data:migrate` when only the seeds files are intended to be run for local development. Even worse is when someone runs `RAILS_ENV=test rails data:migrate` and then we're troubleshooting why their specs are failing _only_ on their machine. Asking for a friend... of course. 😏

**Comment by ilyakatz** [comment]
Hi, currently, there is no configuration like that but that's a good suggestion. Would you be willing to give it a shot in PR. It shouldn't be too difficult. 

1. Update configuration object to include a new config https://github.com/ilyakatz/data-migrate/blob/master/README.md#configuration
2. Easiest way, would be to check for the new config in this method https://github.com/ilyakatz/data-migrate/blob/master/lib/data_migrate/schema_migration_six.rb#L5 so it doesn't think there are any pending migrations

A better way would probably require check in run method https://github.com/ilyakatz/data-migrate/blob/master/lib/data_migrate/schema_migration_six.rb#L14

**Comment by aaronkelton** [comment]
@ilyakatz I think I found an easy solution. Do you see any potential problem with specifying the gem's group in Gemfile? For example:
```ruby
gem 'data_migrate', group: [:staging, :production]
```

Now when I prepend `RAILS_ENV=test` to the migrate command, it will not mess up the test database.
```
% RAILS_ENV=test rails data:migrate
rails aborted!
Don't know how to build task 'data:migrate' (See the list of available tasks with `rails --tasks`)
```

I could not find a way to _exclude_ a specific group, so all desired groups will have to be specified in the Gemfile.

**Comment by ilyakatz** [comment]
That's a reasonable option. Since you're not actually using the code besides as rake tasks, that will be fine. So yeah, it's an easy way for you to accomplish this.
