### ISSUE TITLE
Best practices for running migrations in Production

### ISSUE THREAD

**Issue by harrylewis** [ilyakatz/data-migrate#212]
Hi there 👋🏻 

I just wanted to first say thank you for all the work that has gone in to this gem. It has helped my team,

- Have consistency for our data migrations.
- Provide historical record of our data migrations.

We have bee confused around the timing of running these data migrations in a Production environment. Here are some problems we are encourtering.

1. Ensuring the data migration is run at the correct time from a Product perspective. We may only want to run the data migration **after** a certain point in time.
2. Ensuring the data migration is run at the correct time from a database perspective. We may only want to run the data migration **at** a certain point in time to mitigate application impacts due to a large data migration (millions of records).

Some approaches we have taken/considered are the following.

- Addressing 1: Only merge the data migration once the migration is ready to be run. This is problematic because it is a burden on development. Additionally Product timelines can be volatile.
- Addressing 2: Create team documentation/convention around running migrations using the `up` command, to prevent running all pending data migrations at once. Perhaps also overriding the regular `migrate` task for further protection.

I'm curious to hear from the community if anyone has any other thoughts here!

**Comment by ilyakatz** [comment]
Hm, that's is a very interesting use case. I guess the issues if you have an automated pipeline that runs all database/data migrations together, then you can't do one-off migrations at specified times. To be honest, most of the data migrations that I used as part of this gem were independent so they could be run any time. I almost want to say that it is outside of the the scope of this gem to run scheduled migrations. But theoretically, it can be added as an extra feature - something like an extra meta data for a migration file that would indicate that it should not be run within regular migrate process but should only be run manually.
