### ISSUE TITLE
Did 8.1.1 really introduce a "breaking change"?

### ISSUE THREAD

**Issue by kkurian** [ilyakatz/data-migrate#220]
Upon updating from 8.0.0 to 8.1.1, `bundle install` prints the following notice and instructions:

```
********************************************************************************
data-migrate: IMPORTANT: Breaking change introduced for migrations from v2.

Failure to run the migration can have serious consequences.
See Readme for more info.
********************************************************************************
```

Contrary to the instructions, `README.md` contains no apparent information relating to a breaking change.

The "breaking change" language was [introduced 4 years ago](https://github.com/ilyakatz/data-migrate/blame/39e1bd422b5725720c56147aa5f78170ba09f9d6/data_migrate.gemspec#L44). Is it obsolete? Should it have been triggered by an upgrade from 8.0.0 to 8.1.1?

**Comment by ilyakatz** [comment]
Yeah, you're right, it's probably time to remove this warning. I'll see if I can get to it soon, else, feel free to submit a PR, thanks!
