### ISSUE TITLE
Feature request: Support custom data migration template

### ISSUE THREAD

**Issue by maria-lau** [ilyakatz/data-migrate#224]
It'd be nice if we could could designate a different `data_migration` template in our own repos to be used instead of the default found here: 
https://github.com/ilyakatz/data-migrate/blob/master/lib/generators/data_migration/templates/data_migration.rb

**Comment by ilyakatz** [comment]
Hi there, to be frank, I'm not really adding any new features anymore. Happy to review the code/provide guidance if you're willing to give it a shot and create a PR

**Comment by bazay** [comment]
I've opened a PR implementing this functionality as it's something I was also interested in supporting, thanks.

**Comment by ilyakatz** [comment]
this has been added
