### ISSUE TITLE
Maintanence

### ISSUE THREAD

**Issue by DamirSvrtan** [ilyakatz/data-migrate#23]
Hello there, 

Do you need any help with maintaining this gem? We would love if you could merge https://github.com/ajvargo/data-migrate/pull/21 so I wouldn't have to use a private fork.

Can you please merge this or handout the maintenance to someone else ( me or @janvarljen).

Thank you!

**Comment by ajvargo** [comment]
Hey. I'm not ignoring you. I was on vacation. I'll ping you back in a day or 2. I'll probably handover the maintenance, but want to be sure I'm "done". Thanks for the poke.  I'm amazed folks are using this. :)

Part of maintenance would be to hand over the RubyGems listing too.

**Comment by ajvargo** [comment]
I've just put in the transfer to you @DamirSvrtan.  I'll get the RubyGems bit sorted next.

**Comment by ilyakatz** [comment]
@DamirSvrtan @ajvargo what happened to this, this is a great gem and I would love to see it get some fresh influx. we are using it at https://github.com/execonline-inc so I'm happy to help out as well

**Comment by ajvargo** [comment]
@ilyakatz I don't use this anymore, and am happy to hand it (and the rubygems listing) to anyone who wants to take over. Do you want it? I thought @DamirSvrtan did, but then never heard back.

**Comment by ilyakatz** [comment]
@ajvargo Sure, will keep it going. @DamirSvrtan if you're still interested, happy to share the responsibility.

**Comment by ajvargo** [comment]
Transfer put in. Let me know the e-mail address and I'll make you an owner for the gem on RubyGems.

**Comment by ilyakatz** [comment]
Thanks. I sent you an email to your computer.org account

**Comment by ilyakatz** [comment]
Andrew, actually you don't need to transfer it to me, just add me as collaborator. You're still the original creator, so want to give you the credit. Do you want to do that? (i'll transfer it back to you and you add me a collaborator)?

**Comment by ajvargo** [comment]
Just give me a byline and I'll be happy. I'm clearly not paying much attention to this.:)

**Comment by ilyakatz** [comment]
cool, thank you. will try to address some of the PR's soon!
