### ISSUE TITLE
Incompatible with rails 7.1

### ISSUE THREAD

**Issue by mhenrixon** [ilyakatz/data-migrate#241]
```
bin/rails data:migrate
rails aborted!
NoMethodError: undefined method `create_table' for #<Class:0x000000011b3d5bf0>
/Users/mhenrixon/Code/mhenrixon/consulting/bin/rails:4:in `<main>'
Tasks: TOP => data:migrate
```

**Comment by ilyakatz** [comment]
anyone out there wants to give it a shot to create a PR for this?

**Comment by mhenrixon** [comment]
If noone beats me to it, I'll have a look when I return from vacation. No stress, though, Rails 7.1 isn't released yet :)

**Comment by seanabrahams** [comment]
I suspect [this commit](https://github.com/rails/rails/commit/436277da88507f9aae0874e62f3e61a8546b9683) will be relevant.
