### ISSUE TITLE
undefined method `connection_db_config' for ActiveRecord::Base:Class Did you mean?  connection_config

### ISSUE THREAD

**Issue by adzap** [ilyakatz/data-migrate#258]
There is some version checking in the code for `connection_db_config` but not on this line https://github.com/ilyakatz/data-migrate/blob/ff47fcfac967560028959ef5396572ab8c88af1e/tasks/databases.rake#L207 which breaks in Rails 6.0 at least.

**Comment by ilyakatz** [comment]
interesting, this is the core of the gem, and I would imagine that if it breaks, it would have been reported earlier. what version of the gem are you using? was this a sudden change (eg, when you upgraded)

**Comment by adzap** [comment]
This is version 10 on Rails 6.0. Not sure when this change was implemented, but you seem to have been aware of the incompatibility in other parts https://github.com/ilyakatz/data-migrate/blob/ff47fcfac967560028959ef5396572ab8c88af1e/lib/data_migrate/status_service.rb#LL47C1-L47C1

**Comment by ilyakatz** [comment]
hey @chaunce, this looks to be new from  https://github.com/ilyakatz/data-migrate/commit/0d5e871f5e36eaf4a26fcffa377a77a46dae3fc5, do you know anything about this by any chance? is this a rails 7 thing?

**Comment by chaunce** [comment]
@adzap Can you provide a stack trace or tell me when you get this error?

`ConnectionHandling` changed between Rails 6 and Rails 7, so we do need Rails-version-specific code for each version where Rails connection data is used. If we have a place that's missing this version check around Rails connection data we just need to add it in. I can do some searching later this week as well and see what I can find if I don't hear back.

**Comment by adzap** [comment]
The link to the exact line causing the error is in the issue https://github.com/ilyakatz/data-migrate/blob/ff47fcfac967560028959ef5396572ab8c88af1e/tasks/databases.rake#L207

**Comment by chaunce** [comment]
It appears there's some stubs on some of these connection handling methods in the specs.. I don't have time to review those right now, but this looks like it should resolve your bug https://github.com/ilyakatz/data-migrate/pull/261

**Comment by adzap** [comment]
Yes it will. Thanks. 

Moving this reused code into a helper method on the `DataMigrate` module, perhaps, would dry it up. Not sure if you have helper methods collected somewhere.

**Comment by ilyakatz** [comment]
#261 merged
