### ISSUE TITLE
Add capistrano task for migrating data

### ISSUE THREAD

**Issue by bilby91** [ilyakatz/data-migrate#32]
I have added a cap task in one of my projects for performing data migrations in the deployment pipeline.

@ilyakatz Do you think this can me merged in the gem ? I think that the task should be required in the `Capfile` only.

The rake task is practically identically to `capistrano/rails` `deploy:migrate` task.

```
namespace :deploy do

  desc 'Runs rake data:migrate if migrations are set'
  task :data_migrate => [:set_rails_env] do
    on fetch(:migration_servers) do
      conditionally_migrate = fetch(:conditionally_migrate)
      info '[deploy:data_migrate] Checking changes in /db/data' if conditionally_migrate

      if conditionally_migrate && test("diff -q #{release_path}/db/data #{current_path}/db/data")
        info '[deploy:data_migrate] Skip `deploy:data_migrate` (nothing changed in db/data)'
      else
        info '[deploy:data_migrate] Run `rake data:migrate`'
        invoke :'deploy:data_migrating'
      end
    end
  end

  desc 'Runs rake data:migrate'
  task data_migrating: [:set_rails_env] do
    on fetch(:migration_servers) do
      within release_path do
        with rails_env: fetch(:rails_env) do
          execute :rake, 'data:migrate'
        end
      end
    end
  end

  after 'deploy:migrate', 'deploy:data_migrate'
end

namespace :load do
  task :defaults do
    set :conditionally_migrate, fetch(:conditionally_migrate, false)
    set :migration_role, fetch(:migration_role, :db)
    set :migration_servers, -> { primary(fetch(:migration_role)) }
  end
end
```

If you think this is appropriate I can submit a PR shortly.

Thanks!

**Comment by bilby91** [comment]
I think we will have some issue with this implementation because of the order of the migrations:

```
Data migrations can be created at the same time as schema migrations, or independently. 
Database (db:) tasks have been added and extended to run on data migrations only, or in conjunction with the schema migration. 
For instance, rake db:migrate:with_data will run both schema and data migrations in the **proper order**.
```

**Comment by ilyakatz** [comment]
Hi @bilby91, that is an interesting suggestion. Yes, I think that would be a nice benefit to add a capistrano task. Maybe as a separate task file with instructions on how to include it (since not everyone uses capistrano). 

I am not sure I understand why it would be a problem though

**Comment by bilby91** [comment]
@ilyakatz Thanks for the reply!

The first implementation runs first the schema migrations and then the data migrations. From my understanding, `db:migrate:with_data` run the migrations by timestamp always giving more priority to schema migrations. So, there could be some cases that data could get corrupted if they are not executed in the proper order.

I think that what we can do is, override the default rails migrate implementation and run the migration `:with_data`. What do you think ?

I can make a PR that adds this behaviour and the proper documentation on how to use it.

Thanks!

**Comment by ilyakatz** [comment]
@bilby91 i merged the PR and release a new version https://rubygems.org/gems/data_migrate/versions/2.2.0 , can you give it a try please

**Comment by bilby91** [comment]
@ilyakatz Will update our projects tomorrow and see how it works. 

Thanks!

**Comment by bilby91** [comment]
@ilyakatz it's working correctly. Closing the issue. 😃

**Comment by andresclarity** [comment]
@ilyakatz  this is not working for me,  i added the require  to my capfile:
```
require "capistrano/rails/migrations"
# Capistrano support for data-migrate gem
require 'capistrano/data_migrate'
```
Then in jenkins i have `bundle exec cap ${RAILS_ENV} deploy:migrate --trace` but data migrations don't run .

**Comment by andresclarity** [comment]
I have installed this version `data_migrate (5.2.0)`. Today happen to me, i'm using capistrano capistrano (3.11.0) , (Rails 4.2.6)
