### ISSUE TITLE
Version 9.4.4 yanked

### ISSUE THREAD

**Issue by thomascchen** [ilyakatz/data-migrate#325]
Was version 9.4.4 yanked? I couldn't find a reason why this happened?

```
$ bundle install
Fetching gem metadata from https://rubygems.org/........
Your bundle is locked to data_migrate (9.4.4) from rubygems repository https://rubygems.org/ or installed
locally, but that version can no longer be found in that source. That means the author of data_migrate
(9.4.4) has removed it. You'll need to update your bundle to a version other than data_migrate (9.4.4)
that hasn't been removed in order to install.
```

**Comment by bmulholland** [comment]
got hit with the same

**Comment by ilyakatz** [comment]
sorry about that folks, it was a confusion with versions. since 9.4.4 had a rails upgrade, it was supposed to be major version not minor. please use https://rubygems.org/gems/data_migrate/versions/11.0.0.rc

a few people have volunteered to join the project to help so we're working through some process.

**Comment by ilyakatz** [comment]
once we get a few days of rc version without major complaints, we can promote it 11.0.0

**Comment by klausmeyer** [comment]
Would be nice to have this info in the changelog :)

**Comment by bruno-costanzo** [comment]
I will close this.

**Comment by schinery** [comment]
> once we get a few days of rc version without major complaints, we can promote it 11.0.0

Is 11.0.0 good to release now? Haven't seen any issues raised for it and I've been using it in a Rails 7.2 upgrade that I'd love to get out.

**Comment by ilyakatz** [comment]
@bruno-costanzo looks like RC patch has over 2k downloads so probably safe to promote. i know you added some extra changes to main branch, think those are ok to include in 11.0.0 release? if so, mind doing the release?
