### ISSUE TITLE
11.0.0 release?

### ISSUE THREAD

**Issue by schinery** [ilyakatz/data-migrate#333]
> Is 11.0.0 good to release now? Haven't seen any issues raised for it and I've been using it in a Rails 7.2 upgrade that I'd love to get out.

Posted [this](https://github.com/ilyakatz/data-migrate/issues/325#issuecomment-2318278768) in the closed "Version 9.4.4 yanked" but just for visibility I'm also posting here... can we get an 11.0.0 release out as the RC seems stable?

**Comment by Morozzzko** [comment]
It's live! https://rubygems.org/gems/data_migrate/versions/11.0.0

**Comment by schinery** [comment]
Awesome 👏🏻
