### ISSUE TITLE
Testing for Rails 5

### ISSUE THREAD

**Issue by VagishVela** [ilyakatz/data-migrate#39]
Now that Rails 5 has been out for over a month, we should probably test compatibility.
I am using Rails 5 on a project, this might be an opportunity for me to test it out but it would be nice to have multiple data points so we can ensure things are not broken.

**Comment by ilyakatz** [comment]
I updated travis to have an option for rails5 testing, https://github.com/ilyakatz/data-migrate/blob/master/.travis.yml#L9. I know our test coverage is pretty light for now but I think this is a start. 

If you do wind up testing against rails5 in your project, please let me know. 

Ok to close this ticket?

**Comment by chrishough** [comment]
I just added this to a Rails 5 project and I am seeing this warning...

```
********************************************************************************
data-migrate: --skip-schema-migration option is no longer available as of version 3.0.0
********************************************************************************
```

**Comment by ilyakatz** [comment]
@chrishough this is a warning that is shown for upgrades of data-migrate (whether or not it's was in rails 5). I'm not sure what your question is.

**Comment by chrishough** [comment]
@ilyakatz if it is just a warning, we can ignore it. That is what I was asking.

**Comment by ilyakatz** [comment]
yes, it is a just warning, so if you're not upgrading from a previous version, than you don't have to worry about it

**Comment by VagishVela** [comment]
@ilyakatz Maybe we should only show the warning if upgrading? I got the warning on adding to a new project. Not sure if we can selectively show warnings or not based on conditions.

**Comment by ilyakatz** [comment]
I don’t think it’s possible to selectively show errors.

**Comment by ilyakatz** [comment]
Rails 5 is now supported in the latest release 3.1
