### ISSUE TITLE
Test coverage?

### ISSUE THREAD

**Issue by VagishVela** [ilyakatz/data-migrate#40]
I don't believe this gem has any test coverage as of now, but it might be useful especially as we ensure it works with Rails 5 #39 and also so that nothing breaks as the gem is kept in working order. Especially since we are dealing with data here.

Its pretty cool this has been around for so many years, and I think it is a cool gem.

@ilyakatz If that seems ok to you I was wondering what testing suite we should use? I've had some brief experience with rspec and could help write the tests.

**Comment by ilyakatz** [comment]
Hi @VagishVela that is a great idea (and I'm glad someone finally is keeping me responsible :) ) . I have a lot of experience with rspec so I'm fine with that. Do you want to start a PR? Or if you want I can setup rspec infrastructure for the gem? Let me know

**Comment by VagishVela** [comment]
@ilyakatz I don't mind starting a PR, and we can go from there. It'll be fun.

**Comment by ilyakatz** [comment]
great, let me know if you need any help

**Comment by VagishVela** [comment]
@ilyakatz I've started a PR at #41 and will start adding tests to it. Might make sense to merge it now and make a list of possible tests we want so anyone can branch and work on creating a test.

What are your thoughts?

**Comment by ilyakatz** [comment]
@VagishVela I added travis-ci intergration 

![Alt text](https://monosnap.com/file/L1BetgEQg7A2Lz9hDibyMZeIhiC43f.png)

Do you want to take a stab to more tests?

**Comment by VagishVela** [comment]
Sweet @ilyakatz and yes I will have a stab at more tests.

**Comment by ilyakatz** [comment]
@VagishVela should we keep this open for now? or can i close and can add tests as we go?

**Comment by VagishVela** [comment]
@ilyakatz Yea we can close this.
