### ISSUE TITLE
Post install deprecation warning doesn't specify gem name

### ISSUE THREAD

**Issue by joegesualdo** [ilyakatz/data-migrate#42]
# What
The warning message appears after doing a `bundle install` but it doesn't indicate that the warning stemmed from this gem. (See screenshot below)

# Screenshot
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_111167/2rJbqsWyRLGsqJbC36lvcwwEQtgaBz/1.%2Bjgesualdo%253A%2Btmux%2B%2528zsh%2529%2B2016-10-04%2B11-30-29.png?Expires=1475690633&Signature=Fte83-SZWOmUXgrjNAcU1WaeRuaPkgSlelIlAcRcUnK~3Gjgp3y4XT2FHnZtXXhaxdcCig~8mzYmS10HujuadTxHXQNq18oyUfIVTQu5cLoKC4UbYFc9BSoTBzwGgF2hGSoojFLUzklmLMRoRBzCm-8QX1u4frE2z7~25kfrhqsrtKAhdiCvlnQiM8utLLdgKi06WyimfvdkEEcGZ2eGopVblJYzEUrdVqfc~skzucdfJFdj0b2ccYIpSmDTnu-8J9rEDHMIKCuIKb4~L89TgLV0LyGd2BB5azrAjtuMa1a8E0Poi9Ro~XASUzLppmQ6fwoRdZ140GyRHxLloFcg-Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by ilyakatz** [comment]
good point. created #43
