### ISSUE TITLE
Data migration table removed from schema if data:migrate rake task not run

### ISSUE THREAD

**Issue by VagishVela** [ilyakatz/data-migrate#47]
Is there a better way to keep the data migrate table in the schema? Possibly creating a db:migration on the first `rake data:migrate` and forcing the user to do `rake db:migrate` to run `rake data:migrate`? This way it won't vanish from the schema when one developer in the team hasn't run it.

**Comment by ilyakatz** [comment]
yeah, i think you're right, if you just create a db migration for data_migrations table, that would do the trick. want to give it a try for PR?

**Comment by VagishVela** [comment]
I can have a try. However, how would we address those who already have the
table in there. Does a db migration fail silently if that is the case? Not
sure how rails would address this, I guess I'll know when I try.

On Dec 4, 2016 6:12 PM, "Ilya Katz" <notifications@github.com> wrote:

yeah, i think you're right, if you just create a db migration for
data_migrations table, that would do the trick. want to give it a try for
PR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ilyakatz/data-migrate/issues/47#issuecomment-264688573>,
or mute the thread

**Comment by VagishVela** [comment]
@ilyakatz I'll have a crack this Saturday.

**Comment by ilyakatz** [comment]
Cool, let me know what you find. One option is to have an initial setup instructions that would create db migration

**Comment by ilyakatz** [comment]
ooops, closed by accident. reopened

**Comment by ilyakatz** [comment]
@VagishVela are you still interested in trying this?

**Comment by VagishVela** [comment]
@ilyakatz I totally forgot about this. Wow that was in 2016. Do you think this is still an issue?

**Comment by ilyakatz** [comment]
hi @VagishVela i haven't noticed a problem and no one else reported it, so I'd say let's close it and if it comes up again we can work on it

**Comment by ilyakatz** [comment]
Thanks for the followup!
