### ISSUE TITLE
Rails 5: data_migrate generator generating additional migration file

### ISSUE THREAD

**Issue by travisofthenorth** [ilyakatz/data-migrate#49]
I'm on Rails 5.0.1 and `data_migrate` 2.1.0. Running the generator:
```
➜ rails g data_migration do_it
Running via Spring preloader in process 993
      create  db/migrate/20170202185045_do_it.rb
      create  db/data/20170202185045_do_it.rb
```

**Comment by ilyakatz** [comment]
Hi. What is your question?

**Comment by midu** [comment]
sounds like the issue is that the second file should not be created

**Comment by travisofthenorth** [comment]
@ilyakatz sorry!!! I don't know why I wasn't on the latest version. Just upgraded to 3.0.1 and am no longer experiencing this. Sorry again!

**Comment by ilyakatz** [comment]
No problem at all! I was just chatting work Stephano about today 🙂






On Fri, Feb 3, 2017 at 12:30 PM -0500, "Travis Hunter" <notifications@github.com> wrote:












@ilyakatz sorry!!! I don't know why I wasn't on the latest version. Just upgraded to 3.0.1 and am no longer experiencing this. Sorry again!
