### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported in Rails 5.1

### ISSUE THREAD

**Issue by abreckner** [ilyakatz/data-migrate#53]
More info can be found here

https://github.com/RolifyCommunity/rolify/issues/444.

I did try and do a Pull Request ( https://github.com/ilyakatz/data-migrate/pull/52 ), but I found that this broke on older versions of Rails (so I removed the PR for now).

Thanks

Tony Breckner

**Comment by abreckner** [comment]
Sorry, I was in a bit of a hurry yesterday so I will fill this in a little more now.

As of Rails 5.1 you need to list the Rails version when you create a migration

`RolifyCreateRoles < ActiveRecord::Migration`

becomes

`RolifyCreateRoles < ActiveRecord::Migration[4.2]`

This is because Rails now handles migrations slightly differently according to the version.

So in my fork, I added the migration version into the `lib/data_migrate/migration.rb`.

This is fine for Rails 5 and up, but this naming pattern breaks in older versions of Rails.

So we somehow need to determine the Rails version from the main app and then conditionally pass in a version if it's Rails 5 or higher.

Not sure how to do this off the top of my head.

Thanks

Tony Breckner

**Comment by abreckner** [comment]
Ok, I reopened https://github.com/ilyakatz/data-migrate/pull/52 as it looks like I have fixed the build.

Thanks!

**Comment by ilyakatz** [comment]
this is addressed here https://github.com/ilyakatz/data-migrate/pull/61
