### ISSUE TITLE
data:rollback doesn't execute anything

### ISSUE THREAD

**Issue by mrtibs2000** [ilyakatz/data-migrate#67]
`rake data:rollback` used to work for me. After adding some recent data migrations, when I execute `rake data:rollback`, I get the following output with no execution of the down function:

> DataMigrate::DataSchemaMigration Load (2.9ms)  SELECT "data_migrations".* FROM "data_migrations"
>   ActiveRecord::SchemaMigration Load (2.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"

I tried to identify which one of the 15-20 latest data migrations broke it, but I just can't figure it out. Sometimes it stops running after adding a certain data migration script, but if I drop the database, re-create the schema and reload all the data migrations, that script works (meaning that I can do a rollback on it). I looked at the source code and I noticed it is based on the ActiveRecord migrations rollback functionality. Even so, whatever I did, I still can't figure out why it's not firing the rollback. `rake data:migrate` and `rake db:migrate` and `rake db:rollback` all work just fine (for the new scripts).

**Comment by ilyakatz** [comment]
Hm, is this still the case? I experimented with this and rollback does seem to run the `down` method in the data migration file.

**Comment by mrtibs2000** [comment]
It still happens sometimes. I wasn't able to determine what the common scenario is, but there are certain data migration which still behave like that.

**Comment by ilyakatz** [comment]
Sorry, @mrtibs2000, I am not sure I can do much at this point. I'm slowly refactoring things so perhaps as I go along I find issues. Or if you're able to repro, please open a new bug.
