### ISSUE TITLE
Extend data migrations path

### ISSUE THREAD

**Issue by bodikqlar** [ilyakatz/data-migrate#69]
Hi, folks, you check pending migrations specifying  'db/data' for it, it means Migrator will search only for this folder. Rails has ability to extend migrate path using config.paths['db/migrate'] << 'path to your migration'. Could you add a similar variable to your project?

**Comment by ilyakatz** [comment]
That's a good idea, do you want to give it a shot to draft a PR? I won't be able to get to it for a while, been pretty busy lately.

**Comment by bodikqlar** [comment]
I am a little overloaded right now, but I will find a free time to do it

**Comment by ilyakatz** [comment]
let's keep the ticket open, i think this is a useful feature so would be good to keep in the backlog

**Comment by ilyakatz** [comment]
@andela-denoma what do you think of this request, do you think it makes sense to allow for multiple folders?

**Comment by EnomaDebby** [comment]
If you can add multiple folders for migrations, I think we should be able to do same for data_migrations. However, we'll need to look at the pros and cons of doing that and decide on a way forward.

**Comment by ilyakatz** [comment]
this has been open for two years without progress. probably time to close it out
