### ISSUE TITLE
Loosen restriction on file names to be consistent what Rails supports

### ISSUE THREAD

**Issue by rohitpaulk** [ilyakatz/data-migrate#70]
For schema migrations, rails allows any filename that starts with a number followed by an underscore. 

https://github.com/rails/rails/blob/15ef55efb591e5379486ccf53dd3e13f416564f6/activerecord/lib/active_record/migration.rb#L1103-L1105

i.e. `db/migrate/1001_my_migration.rb` is a valid file name for a migration.  

Data-migrate though, requires that the version number be exactly 14 digits long: https://github.com/ilyakatz/data-migrate/blob/9e67a0555e847a583e570e800577789e4f0956ad/tasks/databases.rake#L142

**Comment by rohitpaulk** [comment]
I'm happy to submit a PR, just wanted to make sure that there aren't any unintended consequences before proceeding. Maybe this will need to be scheduled for the next major release?

**Comment by ilyakatz** [comment]
hi @rohitpaulk, that sounds reasonable. would be great if you could submit a PR. would be nice to see the behavior of what would will happen if there is a mix of long and short names in the mix.

**Comment by ilyakatz** [comment]
hi @rohitpaulk are you still interested in trying this out?

**Comment by rohitpaulk** [comment]
@ilyakatz No... The project I needed this for ended a while ago - we just ended up using the standard format :)

**Comment by ilyakatz** [comment]
ok, will keep this issue open for now, if there is more demand in the near future, i can work on it.

**Comment by ilyakatz** [comment]
since there haven't been any new +1's, i'd like to close it out. if there is new demand in the future we can work on this
