### ISSUE TITLE
Extend to have more migration paths + rake task

### ISSUE THREAD

**Issue by CharlesMcMillan** [ilyakatz/data-migrate#74]
We are successfully using rake data:migrate after our deploys to do non-critical data migrations after the deploy has successfully completed; however, we are realizing that are some data migrations that really should be run a little bit closer to when the schema migration (db/migrate) was run. Ideally what we'd like is to have a db/data1 and db/data2 folders (obviously with better names more descriptive of what they did) that each came with their own rake task like rake data:migrate1 and rake data:migrate2 (also ideally with better names 😄 ) so that our deploy had better control of when they were run. I was a bit excited on seeing this issue [here](https://github.com/ilyakatz/data-migrate/issues/69) but that appears to be a different request... the only solution I can see that achieves what we want here is to fork the gem, change the migrations_path to db/data2, and change the rake task to something like `namespace :<our custom data migration rake task name> do...task...`
This might get the job done but doesn't seem so elegant. Any ideas on how to get what we want here?

**Comment by ilyakatz** [comment]
Hi @CharlesMcMillan yeah, that ticket would solve your problem, but I haven't gotten around to doing it yet. In the meantime, what i think you can do is monkey patch data migrate to override `migrations_path` method inside your different rake tasks

```
irb(main):018:0> DataMigrate::DataMigrator.migrations_path
=> "db/data"
irb(main):019:0> module DataMigrate
irb(main):020:1>   class DataMigrator 
irb(main):021:2>         class << self
irb(main):022:3>             def migrations_path
irb(main):023:4>                 'db/data2'
irb(main):024:4>               end
irb(main):025:3>         end
irb(main):026:2>     end
irb(main):027:1>   end
=> :migrations_path
irb(main):028:0> DataMigrate::DataMigrator.migrations_path
=> "db/data2"
```

Will that work?

**Comment by CharlesMcMillan** [comment]
Would that not override the behavior of rake data:migrate, though? Ideally I'd want a _separate_ rake task that would initiate the migrations under db/data2 with something like `rake data:migrate2` (without overriding `rake data:migrate` so that they both can be used independently

**Comment by ilyakatz** [comment]
Yes, it would override the behavior for that rake task. When you execute another rake task (separate command), it will reload the environment from scratch. 

It certainly is not ideal, but if you need it now that’s an option.

**Comment by CharlesMcMillan** [comment]
Hmmm, that's interesting...I'm not sure I understand yet if this will get me what I want, but I'm wondering if I'm missing what you mean by `When you execute another rake task (separate command), it will reload the environment from scratch.` What I'm trying to get is something like:

Step 1: rake db:migrate
Step 2: rake data:migrate  (runs data migrations from db/data
Step 3: rake data2:migrate (runs data migrations from db/data2)

If I'm understanding what you're saying...I can't run two separate rake tasks that point to different directories without making a code change in between step 2 and 3...Sorry I might be misunderstanding something!

**Comment by ilyakatz** [comment]
Here is what I mean

If you define your data2:migrate like this

```
namespace :data2 do
  task migrate: :environment do
     # override DataMigrate::DataMigrator.migrations_path
  end
end
```

when you execute `rake data2:migrate` it will override DataMigrator for _this_ rake process. However, when you run `rake data:migrate` it will have to reload the full environment from scratch (since it's a new process) and hence it will not run the code above.

downside is that you can't do `rake data:migrate data2:migrate` since it's the same process.

**Comment by CharlesMcMillan** [comment]
I might be missing something, but is the migrations_path being used? I have a breakpoint there and I couldn't get it to hit...I'm thinking the following will work, though:
```ruby
namespace :data do
  task :migrate => :environment do
    assure_data_schema_table
    DataMigrate::DataMigrator.migrate("db/data2/", ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
  end
end
```
Does that make sense? I might also override the table names so that I can have a clear separation between the two tasks, in which case I'll override Migration#table_name and Migrator#schema_migrations_table_name. Unfortunately if I am going to do that, though, I need to also do some major overriding of the `create_table` method in Migrator since the index name needs to be adjusted as well

**Comment by aaronlifton2** [comment]
@CharlesMcMillan Same, i couldn't get any breakpoint to hit. I think `db/data` is just hardcoded somewhere?

**Comment by ilyakatz** [comment]
this has been open two years without much progress. closing
