### ISSUE TITLE
Add data migrations to pending migrations check?

### ISSUE THREAD

**Issue by concept47** [ilyakatz/data-migrate#76]
Would it be possible to 

a. either add a separate configuration variable from the  `config.active_record.migration_error` setting like 

      config.active_record.data_migration_error = :page_load

so that if there is a data migration yet to be run in db/data it throws a pending migration error on page load or ...

b. have db/data be checked as part of the default Rails pending migration check (which would automatically throw an error if there were pending migrations in either db/data or db/migrate)

**Comment by ilyakatz** [comment]
We started this discussion in this PR https://github.com/ilyakatz/data-migrate/pull/58

I like your idea of having a setting for this (where default would be `:silent` or something). I'll need to  see how to go about that. Or, feel free to give it a shot as a PR and i'll provide help ;)

**Comment by ilyakatz** [comment]
Looks like we already have a PR that does something like this https://github.com/ilyakatz/data-migrate/pull/58. So just needs to be adopted to use a new setting

**Comment by ilyakatz** [comment]
closed since #58 is done
