### ISSUE TITLE
Version 3.3.0 Incompatible with SQL Schema Format

### ISSUE THREAD

**Issue by subakva** [ilyakatz/data-migrate#77]
The new data_schema file feature added in 3.3.0 results in an error for projects that use `config.active_record.schema_format = :sql`. The error message is: "only Ruby-based data_schema files are supported at this time".

It seems as if it should be possible to always use the ruby format for the data_schema dump rather than raising an error.

If this line:
https://github.com/ilyakatz/data-migrate/blob/bdca492cbe2a9ece992458e6345c6d41e47c2c3e/tasks/databases.rake#L346

were changed to reference this method:
https://github.com/ilyakatz/data-migrate/blob/bdca492cbe2a9ece992458e6345c6d41e47c2c3e/lib/data_migrate/database_tasks.rb#L9

which could just return the standard ruby file name, rather than raising an error.
https://github.com/ilyakatz/data-migrate/blob/bdca492cbe2a9ece992458e6345c6d41e47c2c3e/lib/data_migrate/database_tasks.rb#L12

I'd be happy to submit a PR if that seems like a reasonable approach.

**Comment by ilyakatz** [comment]
Thanks for filing this bug! Now that you say this, I don't think it makes much sense to use `ActiveRecord::Base.schema_format` for data_migrate schema dumper since it's not really a database object. So yeah, that sounds like a good approach. Let me know if you need help with the PR
