### ISSUE TITLE
Should `data_schema.rb` be committed to repository?

### ISSUE THREAD

**Issue by cabello** [ilyakatz/data-migrate#98]
What's the general advice on `data_schema.rb` should it be committed to repository or ignored? 

The reason I ask is because this file is generated after running `db:migrate:with_data` and I am unsure what happens if I commit it, deploy my application and then execute the rake task in production, does it think the data migration was already run, does it compare the `.rb` file with the version in the database, how does it work?

Thank you kindly

**Comment by ilyakatz** [comment]
This file is used by rake task

```
rake db:schema:load:with_data     # Load both schema.rb and data_schema.rb file into the database
```

However, not everyone has a use-case of needed to use this task. If you don't expect to use it, feel free to ignore it. In my projects, I never use it but I still commit it to git just for bookkeeping purposes. I recommend doing that since there is an upside and not (apparent to me) downside. 

/cc @EnomaDebby

**Comment by ilyakatz** [comment]
I will close this, but if you have questions. Please re-open

**Comment by ravicious** [comment]
Would it be correct to say that one should treat this file the same way as `schema.rb` / `structure.sql`? If so, [the Rails guides recommend committing the file to the repo](https://guides.rubyonrails.org/active_record_migrations.html#schema-dumps-and-source-control).

**Comment by ilyakatz** [comment]
Loosely yes. As you can see, it doesn't actually have any data (as schema and structure), it just stores the latest date of migrations so that if you load it in, you kind of say to data migrate "this is starting point of migrations" so no old migrations need to be run.
